/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CambiosRouteImport } from './routes/cambios'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ComoComprarRouteImport } from './routes/como-comprar'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ProductoCodigoRouteImport } from './routes/producto.$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiosRoute = CambiosRouteImport.update({
  id: '/cambios',
  path: '/cambios',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoComprarRoute = ComoComprarRouteImport.update({
  id: '/como-comprar',
  path: '/como-comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoCodigoRoute = ProductoCodigoRouteImport.update({
  id: '/producto/$codigo',
  path: '/producto/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cambios': typeof CambiosRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contacto': typeof ContactoRoute
  '/terminos': typeof TerminosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$codigo': typeof ProductoCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cambios': typeof CambiosRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contacto': typeof ContactoRoute
  '/terminos': typeof TerminosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$codigo': typeof ProductoCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cambios': typeof CambiosRoute
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/como-comprar': typeof ComoComprarRoute
  '/contacto': typeof ContactoRoute
  '/terminos': typeof TerminosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$codigo': typeof ProductoCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cambios'
    | '/carrito'
    | '/catalogo'
    | '/como-comprar'
    | '/contacto'
    | '/terminos'
    | '/categoria/$slug'
    | '/producto/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cambios'
    | '/carrito'
    | '/catalogo'
    | '/como-comprar'
    | '/contacto'
    | '/terminos'
    | '/categoria/$slug'
    | '/producto/$codigo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cambios'
    | '/carrito'
    | '/catalogo'
    | '/como-comprar'
    | '/contacto'
    | '/terminos'
    | '/categoria/$slug'
    | '/producto/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CambiosRoute: typeof CambiosRoute
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  ComoComprarRoute: typeof ComoComprarRoute
  ContactoRoute: typeof ContactoRoute
  TerminosRoute: typeof TerminosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProductoCodigoRoute: typeof ProductoCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambios': {
      id: '/cambios'
      path: '/cambios'
      fullPath: '/cambios'
      preLoaderRoute: typeof CambiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-comprar': {
      id: '/como-comprar'
      path: '/como-comprar'
      fullPath: '/como-comprar'
      preLoaderRoute: typeof ComoComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$codigo': {
      id: '/producto/$codigo'
      path: '/producto/$codigo'
      fullPath: '/producto/$codigo'
      preLoaderRoute: typeof ProductoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CambiosRoute: CambiosRoute,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  ComoComprarRoute: ComoComprarRoute,
  ContactoRoute: ContactoRoute,
  TerminosRoute: TerminosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProductoCodigoRoute: ProductoCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
